version: '3.7'

services:

  postgres:
    restart: always
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test

  redis:
    restart: always
    image: redis:5.0
    volumes:
      - redis-data:/data

  app:
    &app
    restart: always
    build: .
    volumes:
      - .:/app
    working_dir: /app
    links:
      - postgres:postgres
      - redis:redis
    ports:
      - "8080:8080"
    environment:
      C_FORCE_ROOT: 1
      ALLOWED_HOSTS: "*"
      SECRET_KEY: change-me
      DEBUG: 0
      DATABASE_URL: postgresql://root:root@postgres:5432/test
      BROKER_URL: redis://redis:6379/0
    command: bash -c "cd frontend && yarn install && yarn run build && cd .. && python3 manage.py collectstatic --noinput && python3 manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8080 --reload -k gevent -w 4 -t 900"

  cron:
    <<: *app
    ports:
      - "8081:80"
    command: bash -c "celery --app=config.celery:app beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"

  worker:
    <<: *app
    ports:
      - "8082:80"
    command: bash -c "celery --app=config.celery:app worker --loglevel=INFO --autoscale=4,4 -Q default"

volumes:

  postgres-data:

  redis-data:
