# Generated by Django 3.0.5 on 2021-05-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210528_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
