# Generated by Django 3.0.5 on 2021-06-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210530_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='geo_lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postitem',
            name='geo_long',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postitem',
            name='geoip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postitem',
            name='promotion_type',
            field=models.CharField(blank=True, choices=[('dsad', 'dsds')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Campaign', 'Promotion'), ('Diary', 'Diary'), ('Hotline', 'Hotline'), ('Event', 'Event'), ('Service', 'Services'), ('Support', 'Support-Groups'), ('Initiative', 'Initiative'), ('Share', 'Share'), ('Mood', 'Mood'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='visibility_type',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=255, null=True),
        ),
    ]
