# Generated by Django 3.0.5 on 2021-06-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210621_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postitem',
            name='mood_type',
            field=models.CharField(blank=True, choices=[('Angry', 'angry'), ('Sad', 'sad'), ('Meh', 'meh'), ('Satisfied', 'satisfied'), ('Happy', 'happy')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Promotion', 'promotion'), ('Status', 'status'), ('Diary', 'diary'), ('Request', 'request'), ('Offer', 'offer')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='promotion_type',
            field=models.CharField(blank=True, choices=[('Campaign', 'campaign'), ('Event', 'event'), ('Hotline', 'hotline'), ('Service', 'service'), ('Group', 'group'), ('Initiative', 'initiative'), ('Article', 'article'), ('Ads', 'ads'), ('Other', 'other')], max_length=255, null=True),
        ),
    ]
