# Generated by Django 3.0.5 on 2021-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_postcommentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
