# Generated by Django 3.0.5 on 2021-05-23 05:17

import apps.account.generators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=40)),
                ('anonymous', models.CharField(blank=True, default=apps.account.generators.generate_anonymous_username, max_length=255, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_color', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('weblink', models.URLField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('office_start_time', models.TimeField(blank=True, null=True)),
                ('office_end_time', models.TimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('state', models.CharField(db_index=True, default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=40)),
                ('state', models.CharField(db_index=True, default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='account.Profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='account.Profile')),
            ],
        ),
    ]
