# Generated by Django 3.0.5 on 2021-05-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210523_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
