# Generated by Django 3.0.5 on 2021-05-30 05:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='profile_followers', through='account.ProfileFollower', to='account.Profile'),
        ),
        migrations.CreateModel(
            name='ProfileConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=40)),
                ('status', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('state', models.CharField(db_index=True, default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connectee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectee', to='account.Profile')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector', to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='profile_connections', through='account.ProfileConnection', to='account.Profile'),
        ),
    ]
