# Generated by Django 3.0.5 on 2021-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210619_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
