# Generated by Django 3.0.5 on 2021-06-21 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210620_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(db_index=True, default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportee', to='account.Profile')),
                ('reported_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='account.Profile')),
            ],
        ),
    ]
