# Generated by Django 3.0.5 on 2021-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profilereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilereport',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
