# Generated by Django 3.0.5 on 2021-06-21 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profilereport_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=40)),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(db_index=True, default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=40)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('attrs_json', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=50, null=True)),
                ('state', models.CharField(db_index=True, default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='documents', to='account.Document'),
        ),
        migrations.AddField(
            model_name='profile',
            name='supports',
            field=models.ManyToManyField(blank=True, related_name='supports', to='account.Support'),
        ),
    ]
