# Generated by Django 3.0.5 on 2021-06-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210621_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='connections',
        ),
    ]
