# Generated by Django 3.0.5 on 2021-06-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_chatroom_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
    ]
