# Generated by Django 3.0.5 on 2021-06-23 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postitem_help_type'),
        ('account', '0013_auto_20210623_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='post.PostItem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='documents',
            field=models.ManyToManyField(blank=True, to='account.Document'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='supports',
            field=models.ManyToManyField(blank=True, to='account.Support'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=40)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('attrs_json', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_readed', models.BooleanField(default=False)),
                ('state', models.CharField(db_index=True, default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Profile')),
            ],
        ),
    ]
